version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true

    steps:
      - checkout
      - run:
          name: Setup filesystem
          command: |
            cp config/database.yml.docker config/database.yml 
            cp .env.docker .env
      - run:
          name: Docker Compose
          command: docker-compose -f docker-compose.test.yml up -d
      - run:
          name: Wait for DB
          command: timeout 5m bash -c "until docker-compose -f docker-compose.test.yml exec postgres pg_isready ; do sleep 5 ; done"
      - run:
          name: Tests
          command: docker-compose -f docker-compose.test.yml exec -e RAILS_ENV=test website bash -c "bundle install && rake db:drop db:create db:migrate && rspec"

